version: '2'
services:
  mongo:
    image: mongo
  library:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_NAME=library
      - DB_HOST=mongo
