INSERT INTO AUTHORS (AUTHOR_ID, AUTHOR_NAME, AUTHOR_LASTNAME) VALUES (1, 'Дуглас', 'Адамс');
INSERT INTO AUTHORS (AUTHOR_ID, AUTHOR_NAME, AUTHOR_LASTNAME) VALUES (2, 'Джон', 'Толкин');
INSERT INTO AUTHORS (AUTHOR_ID, AUTHOR_NAME, AUTHOR_LASTNAME) VALUES (3, 'Stiven', 'King');

INSERT INTO GENRES (GENRE_ID, GENRE_NAME) VALUES (1, 'фантастика');
INSERT INTO GENRES (GENRE_ID, GENRE_NAME) VALUES (2, 'фэнтези');
INSERT INTO GENRES (GENRE_ID, GENRE_NAME) VALUES (3, 'стихи');

INSERT INTO BOOKS (BOOK_ID, BOOK_NAME, BOOK_SUMMARY, AUTHOR_ID, GENRE_ID) VALUES (1, 'Автостопом по галактике', 'Путеводитель для путешествующих по галактике автостопом', 1, 1);
INSERT INTO BOOKS (BOOK_ID, BOOK_NAME, BOOK_SUMMARY, AUTHOR_ID, GENRE_ID) VALUES (2, 'Властелин Колец', 'Одно из самых известных произведений жанра фэнтези', 2, 2);

INSERT INTO COMMENTS (COMMENT_SEND_DATE, COMMENT_TEXT, COMMENT_USERNAME, BOOK_ID) VALUES ('2019-01-22 15:34:08', 'Главный вопрос жизни, Вселенной и всего такого?', 'test', 1);
INSERT INTO COMMENTS (COMMENT_SEND_DATE, COMMENT_TEXT, COMMENT_USERNAME, BOOK_ID) VALUES ('2019-01-22 15:34:15.5', '42', 'Deep Thought', 1);
