DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS (
    AUTHOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    AUTHOR_NAME VARCHAR(255),
    AUTHOR_LASTNAME VARCHAR(256)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES (
    GENRE_ID INT PRIMARY KEY AUTO_INCREMENT,
    GENRE_NAME VARCHAR(255)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS (
    BOOK_ID INT PRIMARY KEY AUTO_INCREMENT,
    BOOK_NAME VARCHAR(255),
    BOOK_SUMMARY VARCHAR(1024),
    AUTHOR_ID INT,
    GENRE_ID INT
);

ALTER TABLE BOOKS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (AUTHOR_ID);
ALTER TABLE BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES (GENRE_ID);