DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    LASTNAME VARCHAR(256)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    SUMMARY VARCHAR(1024),
    AUTHOR_ID INT,
    GENRE_ID INT
);

ALTER TABLE BOOKS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID);
ALTER TABLE BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID);