INSERT INTO AUTHORS (ID, NAME, LASTNAME) VALUES (1, 'Name1', 'LastName1');
INSERT INTO AUTHORS (ID, NAME, LASTNAME) VALUES (2, 'Name2', 'LastName2');
INSERT INTO AUTHORS (ID, NAME, LASTNAME) VALUES (3, 'Name3', 'LastName3');


INSERT INTO GENRES (ID, NAME) VALUES (1, 'Genre1');
INSERT INTO GENRES (ID, NAME) VALUES (2, 'Genre2');
INSERT INTO GENRES (ID, NAME) VALUES (3, 'Genre3');

INSERT INTO BOOKS (ID, NAME, SUMMARY, AUTHOR_ID, GENRE_ID) VALUES (1, 'Book_Name1', 'Book_Summary1', 1, 1);
INSERT INTO BOOKS (ID, NAME, SUMMARY, AUTHOR_ID, GENRE_ID) VALUES (2, 'Book_Name2', 'Book_Summary2', 2, 2);