INSERT INTO AUTHOR (ID, NAME, LASTNAME) VALUES (1, 'Name1', 'LastName1');
INSERT INTO AUTHOR (ID, NAME, LASTNAME) VALUES (2, 'Name2', 'LastName2');
INSERT INTO AUTHOR (ID, NAME, LASTNAME) VALUES (3, 'Name3', 'LastName3');


INSERT INTO GENRE (ID, NAME) VALUES (1, 'Genre1');
INSERT INTO GENRE (ID, NAME) VALUES (2, 'Genre2');
INSERT INTO GENRE (ID, NAME) VALUES (3, 'Genre3');

INSERT INTO BOOK (ID, NAME, SUMMARY, AUTHOR_ID, GENRE_ID) VALUES (1, 'Book_Name1', 'Book_Summary1', 1, 1);
INSERT INTO BOOK (ID, NAME, SUMMARY, AUTHOR_ID, GENRE_ID) VALUES (2, 'Book_Name2', 'Book_Summary2', 2, 2);

INSERT INTO COMMENT (SEND_DATE, TEXT, USERNAME, BOOK_ID) VALUES ('2019-01-01 12:00:08', 'comment1', 'user1', 1);
INSERT INTO COMMENT (SEND_DATE, TEXT, USERNAME, BOOK_ID) VALUES ('2019-01-01 15:00:16', 'comment2', 'user2', 1);
