INSERT INTO AUTHORS (AUTHOR_ID, AUTHOR_NAME, AUTHOR_LASTNAME) VALUES (1, 'Name1', 'LastName1');
INSERT INTO AUTHORS (AUTHOR_ID, AUTHOR_NAME, AUTHOR_LASTNAME) VALUES (2, 'Name2', 'LastName2');
INSERT INTO AUTHORS (AUTHOR_ID, AUTHOR_NAME, AUTHOR_LASTNAME) VALUES (3, 'Name3', 'LastName3');


INSERT INTO GENRES (GENRE_ID, GENRE_NAME) VALUES (1, 'Genre1');
INSERT INTO GENRES (GENRE_ID, GENRE_NAME) VALUES (2, 'Genre2');
INSERT INTO GENRES (GENRE_ID, GENRE_NAME) VALUES (3, 'Genre3');

INSERT INTO BOOKS (BOOK_ID, BOOK_NAME, BOOK_SUMMARY, AUTHOR_ID, GENRE_ID) VALUES (1, 'Book_Name1', 'Book_Summary1', 1, 1);
INSERT INTO BOOKS (BOOK_ID, BOOK_NAME, BOOK_SUMMARY, AUTHOR_ID, GENRE_ID) VALUES (2, 'Book_Name2', 'Book_Summary2', 2, 2);